### ISSUE TITLE
Error during the count_output.pl

### ISSUE THREAD

**Issue by surendravikram** [kbseah/phylogenomics-tools#1]
Hi,
Thank you for creating such a nice package. 
Currently, I am trying to extract the single copy marker genes using AMPHORA2. When I ran the script "count_output.pl" it gives me an error **"readline() on closed filehandle MANFO at /home/phylogenomics-tools-master/count_output.pl line 174"**. I think the error is with the marker genes which have not been extracted for some genomes. Can you suggest some edits in script.
Thanks,

Surendra

**Comment by kbseah** [comment]
Hello Surendra,

Thanks for giving the scripts a try. Could you copy here the exact commands you used for the first three steps of the pipeline? Could have been a bug in the earlier steps.

Cheers,
Brandon

**Comment by surendravikram** [comment]
Hi Brandon,

Thanks for the reply. 
I Ran the first two commands and did not get any error
1. perl  ~/Softwares/phylogenomics-tools-master/rename_fasta_from_table.pl --file Genomes-rename.txt --orig /localdata/svikram/Genome-marker/ --wd working-dir
2. perl  ~/Softwares/phylogenomics-tools-master/extract_markers.pl --file ./Genomes-rename.txt --wd /localdata/svikram/Genome-marker/working-dir  --amphora_path /home/surendrav/Softwares/AMPHORA2-master

but the third command retuned the above error
perl  ~/Softwares/phylogenomics-tools-master/count_output.pl --file Genomes-rename.txt --wd /localdata/svikram/Genome-marker/working-dir --markers all-amphora-marker.txt

I found that most of the genomes have missing marker genes which may be the issue for this error.

**Comment by kbseah** [comment]
Hm... could you run `ls` on the folder `working-dir` and copy the output here?

**Comment by kbseah** [comment]
and also attach the files `Genomes-rename.txt` and `all-amphora-marker.txt` ?

**Comment by surendravikram** [comment]
[marker-amphora.txt](https://github.com/kbseah/phylogenomics-tools/files/578734/marker-amphora.txt)
[marker-amphora.txt](https://github.com/kbseah/phylogenomics-tools/files/578735/marker-amphora.txt)

Find below the ls output:

counts_table_protein  genome_13  genome_18  genome_22  genome_27  genome_31  genome_36  genome_40  genome_45  genome_5   genome_54  genome_59  genome_63
genome_1              genome_14  genome_19  genome_23  genome_28  genome_32  genome_37  genome_41  genome_46  genome_50  genome_55  genome_6   genome_64
genome_10             genome_15  genome_2   genome_24  genome_29  genome_33  genome_38  genome_42  genome_47  genome_51  genome_56  genome_60  genome_7
genome_11             genome_16  genome_20  genome_25  genome_3   genome_34  genome_39  genome_43  genome_48  genome_52  genome_57  genome_61  genome_8
genome_12             genome_17  genome_21  genome_26  genome_30  genome_35  genome_4   genome_44  genome_49  genome_53  genome_58  genome_62  genome_9

I can see the output "counts_table_protein" is this correct?

**Comment by kbseah** [comment]
Is there any content in the file `counts_table_protein`?

**Comment by surendravikram** [comment]
Actually, I didn't check the output directory due to the errors. Yes, the output table "counts_table_proteins" has contents in it. I will check the result manually.

**Comment by kbseah** [comment]
Sure let me know if the results appear consistent with the Amphora2 results or not. I think the error message pops up because the way the script handles missing markers is not very clever. Sorry about the inconvenience! I appreciate the bug report

**Comment by kbseah** [comment]
Should be fixed with commit 5bdcf56bd8904bcde658a2d5d188f5732089f88c

**Comment by surendravikram** [comment]
Hi Brandon,

I checked the output from the AMPHORA2 and found the similar results in the table obtained from  phylogenomics script count_output.pl 

Thanks again

Surendra

**Comment by kbseah** [comment]
Welcome! Thanks for bringing to my attention
