### ISSUE TITLE
Renaming table file not found: No such file or directory at rename_fasta_from_table.pl line 111.

### ISSUE THREAD

**Issue by jade-davies** [kbseah/phylogenomics-tools#8]
Hello,

I am having an error at step 1 in renaming the fasta files. 
I have made the RENAME_TABLE.txt with the original name of the fasta file and the desired name (under 10 characters).

[RENAME_TABLE.txt](https://github.com/kbseah/phylogenomics-tools/files/5246286/RENAME_TABLE.txt)

When I am trying to run the first command:

`perl /qib/research-groups/Arjan-Narbad/shared_tools/phylogenomics-tools-master/rename_fasta_from_table.pl \ --file /qib/research-groups/Arjan-Narbad/davies/phylogenomic_tree/RENAME_TABLE.txt \ --orig /qib/research-groups/Arjan-Narbad/davies/phylogenomic_tree/original_fasta/ \ --wd /qib/research-groups/Arjan-Narbad/davies/phylogenomic_tree/NEW_WORKING_FOLDER/`

I am getting the error:

`Renaming table file not found: No such file or directory at /qib/research-groups/Arjan-Narbad/shared_tools/phylogenomics-tools-master/rename_fasta_from_table.pl line 111.`

It seems like the rename_table.txt file is not being recognised but I'm struggling to see where the problem is coming from. Do you have any thoughts about it?
Thank you in advance!

**Comment by kbseah** [comment]
Hello @jade-davies ,

That's strange indeed.. could it be a permissions problem? Are you running the script under the same user account as when you created the files?

By the way these scripts are pretty old, you might consider trying something newer like the ete-build pipeline from the ete3 toolkit http://etetoolkit.org/documentation/ete-build/

Cheers,
Brandon

**Comment by kbseah** [comment]
Closing inactive

**Comment by kbseah** [comment]
closing inactive

**Comment by kbseah** [comment]
Closing inactive
